[
  inputs: ["mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
  import_deps: [:ecto, :phoenix],
  locals_without_parens: [
      ## migration
      create: :*,
      create_if_not_exists: :*,
      alter: :*,
      drop: :*,
      drop_if_exists: :*,
      rename: :*,
      add: :*,
      remove: :*,
      modify: :*,
      execute: :*,

      ## phoenix 1.4.0-dev import here -- remove after migration to it
      intercept: 1,
      connect: 3,
      connect: 4,
      delete: 3,
      delete: 4,
      forward: 2,
      forward: 3,
      forward: 4,
      get: 3,
      get: 4,
      head: 3,
      head: 4,
      match: 4,
      match: 5,
      options: 3,
      options: 4,
      patch: 3,
      patch: 4,
      pipeline: 2,
      pipe_through: 1,
      post: 3,
      post: 4,
      put: 3,
      put: 4,
      resources: 2,
      resources: 3,
      resources: 4,
      trace: 4,
      action_fallback: 1,
      plug: 1,
      plug: 2,
      socket: 2,
      socket: 3,
      channel: 2,
      channel: 3,
      assert_broadcast: 2,
      assert_broadcast: 3,
      assert_push: 2,
      assert_push: 3,
      assert_reply: 2,
      assert_reply: 3,
      assert_reply: 4,
      refute_broadcast: 2,
      refute_broadcast: 3,
      refute_push: 2,
      refute_push: 3,
      refute_reply: 2,
      refute_reply: 3,
      refute_reply: 4,
      assert_error_sent: 2
    ]
]
